// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ChanDoanXray.Models
{
    [Table("BenhNhan")]
    public partial class BenhNhan
    {
        public BenhNhan()
        {
            TiepNhans = new HashSet<TiepNhan>();
        }

        [Key]
        public int Id { get; set; }

        [StringLength(255)]
        public string? MaYTe { get; set; }

        public string? TenBenhNhan { get; set; }

        [StringLength(10)]
        public string? GioiTinh { get; set; }

        public DateTime? NgaySinh { get; set; }

        [StringLength(50)]
        public string? SoDienThoai { get; set; }

        [StringLength(500)]
        public string? DiaChiChiTiet { get; set; }

        public DateTime? NgayTao { get; set; }

        public int? NguoiTao { get; set; }

        public bool? Huy { get; set; }

        [ForeignKey("NguoiTao")]
        [InverseProperty("BenhNhans")]
        public virtual User NguoiTaoNavigation { get; set; }
        [InverseProperty("BenhNhan")]
        public virtual ICollection<TiepNhan> TiepNhans { get; set; }
    }
}