// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using ChanDoanXray.DTOs;
using Microsoft.EntityFrameworkCore;

namespace ChanDoanXray.Models
{
    [Table("LinkFile")]
    public partial class LinkFile
    {
        [Key]
        public int Id { get; set; }
        [StringLength(255)]
        public string DuongDanGoc { get; set; }
        public string FilenameGoc { get; set; }
        [StringLength(255)]
        public string Loai { get; set; }
        public bool? Huy { get; set; }
        public string DuongDanChanDoan { get; set; }
        public string FilenameChanDoan { get; set; }
        public string chanDoan { get; set; }
        public int? TiepNhanId { get; set; }

        [ForeignKey("TiepNhanId")]
        [InverseProperty("LinkFiles")]
        public virtual TiepNhan TiepNhan { get; set; }
    }
}