// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ChanDoanXray.Models
{
    [Table("NhanVien")]
    public partial class NhanVien
    {

        [Key]
        public int Id { get; set; }
        [StringLength(255)]
        public string HoVaTen { get; set; }
        public int? NamSinh { get; set; }
        public bool? Huy { get; set; }
        public int? UserId { get; set; }
        public DateTime? NgayTao { get; set; }
        [StringLength(255)]
        public string Email { get; set; }
        [StringLength(50)]
        public string SoDienThoai { get; set; }
        [StringLength(255)]
        public string DiaChi { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("NhanViens")]
        public virtual User User { get; set; }
    }
}
