// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ChanDoanXray.Models;

namespace ChanDoanXray.Models
{
    [Table("TiepNhan")]
    public partial class TiepNhan
    {
        [Key]
        public int Id { get; set; }

        public int? BenhNhanId { get; set; }

        public bool? TrangThai { get; set; } // chỉ là một cờ trạng thái, không cần [ForeignKey]

        public DateTime? NgayTao { get; set; }
        public bool? Huy { get; set; }

        [ForeignKey("BenhNhanId")]
        [InverseProperty("TiepNhans")]
        public virtual BenhNhan BenhNhan { get; set; }

        [InverseProperty("TiepNhan")]
        public virtual ICollection<LinkFile> LinkFiles { get; set; }
    }
}