// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ChanDoanXray.Models
{
    [Table("User")]
    [Index("Email", Name = "User_Email", IsUnique = true)]
    [Index("Username", Name = "User_Username", IsUnique = true)]
    public partial class User
    {
        public User()
        {
            BenhNhans = new HashSet<BenhNhan>();
            UserRoles = new HashSet<UserRole>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        public string Username { get; set; }
        [StringLength(255)]
        public string Password { get; set; }
        [StringLength(255)]
        public string Email { get; set; }
        public string DiaChi { get; set; }
        [StringLength(11)]
        public string SoDienThoai { get; set; }
        public bool? Huy { get; set; }

        [InverseProperty("NguoiTaoNavigation")]
        public virtual ICollection<BenhNhan> BenhNhans { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
