// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using ChanDoanXray.Models;

namespace ChanDoanXray.Models
{
    public partial class XrayContext : DbContext
    {
        public XrayContext()
        {
        }

        public XrayContext(DbContextOptions<XrayContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TiepNhan> TiepNhans { get; set; }
        public virtual DbSet<BenhNhan> BenhNhans { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<LinkFile> LinkFiles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BenhNhan>(entity =>
            {
                entity.HasOne(d => d.NguoiTaoNavigation)
                    .WithMany(p => p.BenhNhans)
                    .HasForeignKey(d => d.NguoiTao)
                    .HasConstraintName("BenhNhan_User_Id_fk");
            });
            modelBuilder.Entity<TiepNhan>(entity =>
            {
                entity.HasOne(d => d.BenhNhan)
                    .WithMany(p => p.TiepNhans)
                    .HasForeignKey(d => d.BenhNhanId)
                    .HasConstraintName("TiepNhan_BenhNhan_Id_fk");
            });


            modelBuilder.Entity<LinkFile>(entity =>
            {
                entity.HasOne(d => d.TiepNhan)
                    .WithMany(p => p.LinkFiles)
                    .HasForeignKey(d => d.TiepNhanId)
                    .HasConstraintName("LinkFile_TiepNhan_Id_fk");
            });
            modelBuilder.Entity<UserRole>(entity =>
            {
                entity.HasOne(d => d.Role)
                    .WithMany(p => p.UserRoles)
                    .HasForeignKey(d => d.RoleId)
                    .HasConstraintName("User_Role_Role_Id_fk");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.UserRoles)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("User_Role_User_Id_fk");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}